changelog:
  exclude:
    labels:
      - duplicate
      - question
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🧰 Refactor
      labels:
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
