name: PR Checks

on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checks for label
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'bug, enhancement, grasshopper, dynamo, documentation, refactor'
        invalid-labels: 'help wanted, duplicate, question'
