name: PR Checks
# https://github.com/marketplace/actions/verify-pull-request-labels
# https://github.com/marketplace/actions/pr-title-checker
# https://github.com/marketplace/actions/check-pull-request-title

on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize, edited]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checks for label
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'bug, enhancement, grasshopper, dynamo, documentation, refactor'
        invalid-labels: 'help wanted, duplicate, question'

    - name: Checks PR title
      uses: Slashgear/action-check-pr-title@v3.0.0
      with:
        regexp: '([a-z])+'
