name: Repository Dispatch
on:
  push:
    branches: main
  
jobs:
  build:
    #if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          
      - name: 💾 7Zip library
        #working-directory: ./library
        run: 7z a -t7z -mx=9 MMLibrary.7z .\library\* -x!*.gitignore
        
      - name: Upload revision
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: MMLibrary.7z
